### ISSUE TITLE
[translation discussion] Parameter

### ISSUE THREAD

**Issue by erfannoury** [erfannoury/persian-ml-glossary#1]
<div dir="rtl">
یکی از کلماتی که ترجمه‌ی خوبی براش پیدا نکردیم کلمه‌ی Parameter هست.

جست‌وجوی کلمه‌ی Parameter و «پارامتر» در سایت واژه‌یاب این نتایج رو میده:

* [Parameter](https://www.vajehyab.com/wiki/parameter) (واژه‌نامه‌ی آزاد)
  فراسنج
* [عامل](https://www.vajehyab.com/farhangestan/%D8%B9%D8%A7%D9%85%D9%84) (واژه‌های مصوب فرهنگستان)
 

>  [عمومی] هر عنصر یا جزء مهمی که سامانه‌ای را تعریف می‌کند و کار آن را تعیین یا محدود می‌کند متـ . مؤلفه

* [پارامتر](https://www.vajehyab.com/moein/%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1) (فرهنگ فارسی معین)

> (مِ) [ فر. ] (اِ.) 1 - مقدار ثابت دلخواهی که به ازاء هر یک از مقادیر آن عضوی از یک دستگاه مشخص شود. 2 - متغیری که می توان دو یا چند تابع را برحسب آن بیان کرد. استعمال پارامترها در ریاضیات و فیریک و غیره بسیار معمول و مهم است . 3 - در قطع های مخروطی ، نصف طول وتری که از یک کانون به محور کانونی عمود شود. معمولاً آن را به P نمایش می دهند.

همچنین به توضیحات و معانی این کلمه در [لغت‌نامه‌ی Merriam-Webster](https://www.merriam-webster.com/dictionary/parameter)، در [لغت‌نامه‌ی آکسفورد](https://en.oxforddictionaries.com/definition/parameter)، و در [مرجع ریاضیات Wolfram](http://mathworld.wolfram.com/Parameter.html) توجه کنید.

در [ویکیپدیای فارسی](https://fa.wikipedia.org/wiki/%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1) این کلمه به صورت «عامل»، «مولفه»، و «پارامتر» ترجمه شده.

در [واژه‌نامه‌ی پردازش سیگنال آزمایشگاه پردازش تصویر دانشگاه شریف](http://ipl.ce.sharif.edu/download/IPL%20Glossary.pdf) هم ترجمه‌ی این کلمه «عامل» داده شده است.

همچنین @momeni برای ترجمه‌ی این کلمه واژه‌ی «دانسته» رو پیشنهاد دادن و در [اینجا توضیحات بیشتری](https://github.com/erfannoury/cheatsheet-translation/issues/3#issuecomment-429215858) هم ارائه کردن.

-------

* ترجمه‌ی «عامل» به دلیل اینکه کلمه‌ی Agent هم به «عامل» ترجمه میشه و در ادبیات یادگیری ماشین هر دو کلمات به تنهایی و یا حتی در کنار هم استفاده میشن، ترجمه‌ی مناسبی نیست. برای مثال ترجمه‌ی عبارت "Parameters of the agent"، «عوامل عامل» خواهد بود.
* ترجمه‌ی «دانسته» هم از نظر معنایی نوعی تضاد رو منتقل می‌کنه. در ادبیات یادگیری ماشین بیشتر اوقات از عباراتی استفاده میشه که حاوی معنای تخمین مقدار یک یا چند Parameter است. اگر Parameter به کلمه‌ی «دانسته» ترجمه بشه، در این صورت عبارت «تخمین دانسته» مقداری متناقض به نظر میرسه.
* برای حالتی که به دنبال «برآورد پارامتری (این بار با مقداری نادانسته) از یک توزیع آماری هستیم»[۱]، @momeni ترجمه‌ی «فراسنج» رو پیشنهاد دادن. مشکل این ترجمه هم نیاز به ترجمه‌ی کلمه‌ی Hyperparameter هست که این کلمه هم به وفور در ادبیات یادگیری ماشین استفاده میشه. بنابراین هر ترجمه‌ای که برای کلمه‌ی Parameter در نظر گرفته بشه باید قابل تعمیم به ترجمه‌ی Hyperparameter با اضافه کردن پیشوند «فرا» باشه.
</div>

[1] https://github.com/erfannoury/cheatsheet-translation/issues/3#issuecomment-429215858

**Comment by erfannoury** [comment]
<div dir="rtl">
اولین بحث رو در این مخزن ایجاد کردم. لطفاً نظر بدید.

@m-karimi @momeni @reza1615 @yassersouri @kazemnejad @AlisterTA

اگر افراد دیگری هم هستن که می‌تونن به این بحث کمک بکنن لطفاً به اون‌ها هم اطلاع بدید.

**Comment by momeni** [comment]
hyperparameter: ابرفراسنج

**Comment by erfannoury** [comment]
<div dir="rtl">

راست میگید، اینطوری بهش فکر نکردم. در این صورت به نظر میاد که «**فراسنج**» ترجمه‌ی خوبی برای این کلمه باشه.
نظر بقیه چیه؟

**Comment by mhd-karimi** [comment]
اگه کلمه‌ای مستقیما تو فارسی استفاده میشه، من ترجیح میدم از همون کلمه استفاده کنم. در اینجا کلمه پارامتر چون در فرهنگ معین اومده و در مکالمات (خارج از مباحث یادگیری ماشین) کاربرد داره و به صورت خیلی معمول استفاده میشه، به شخصه ترجیحم بر استفاده از خود کلمه **پارامتر** است و یا در نهایت استفاده از کلمه **عامل** به جای این‌که معادل جدیدی معرفی بشه

**Comment by erfannoury** [comment]
@m-karimi کلمه‌ی عامل که بخاطر مشکلاتی که بالا گفتم ترجمه‌ی مناسبی نیست. ولی اینکه استفاده از پارامتر خوبه یا ترجمه‌ی دیگه‌ای رو باید استفاده کنیم در حال حاضر نمی‌دونم.

**Comment by erfannoury** [comment]
<div dir="rtl">
@alicheh توی کتاب شهشهانی برای این کلمه چه ترجمه‌ای به کار رفته؟

**Comment by erfannoury** [comment]
<div dir="rtl">
با توجه به اینکه بیش از یک ماه هست که پیشنهاد جدیدی برای این کلمه اعلام نشده فردا این مبحث بسته خواهد شد.

**Comment by erfannoury** [comment]
https://github.com/erfannoury/persian-ml-glossary/commit/2b60e8285e4796683e580d2db331dfd69abe562c closes this issue.

**Comment by erfannoury** [comment]
<div dir="rtl">
@momeni ممنونم از پیشنهادتون.
