### ISSUE TITLE
[translation discussion] Attention

### ISSUE THREAD

**Issue by erfannoury** [erfannoury/persian-ml-glossary#5]
<div dir="rtl">
کلمه‌ی Attention هم یکی از کلماتی هست که کاربرد بسیاری داره. این کلمه بیشتر «توجه» و یا «وقت» ترجمه شده [۱]، ولی این ترجمه‌ها خیلی مناسب به نظر نمی‌رسن، یا اینکه چون به اندازه‌ی کافی ازشون استفاده نشده غیرعادی به نظر میرسن.

فکر می‌کنم این کلمه در گفتمان یادگیری عمیق بیشتر بخاطر [۲] مطرح شد.

------------------

</div>

[1] https://www.vajehyab.com/farhangestan/توجه
[2] [Neural Machine Translation by Jointly Learning to Align and Translate](https://arxiv.org/abs/1409.0473)

**Comment by MohsenFayyaz89** [comment]
<div dir='rtl'>
به نظرم «توجه» معنی مناسبی می تونه داشته باشه ولی دلیلم برای انتخاب «نگرش» در نظر گرفتن تلفظ آوایی این واژه بود 
</div>

**Comment by AlisterTA** [comment]
<div dir='rtl'>

در نورو ساینس این کلمه به `توجه `معنی شده اما در یادگیری عمیق [به نظر شخص من] مفهوم قابل لمسی نیست.
@MohsenFayyaz89 `نگرش` را پیشنهاد دادند. این کلمه در فرهنگ لغت به عنوان مترادف کلمه `توجه` آورده شده، اما به نظر من نگرش یک مفهمو عام تر از توجه است. `توجه `همراه با حضور در لحظه (mindfulness) هست. `نگرش` یک جورایی طریق دیدن است.
کلمه ای که انتخاب میشه همچنین باید به شکلی باشه که در ترجمه مفاهیم زیر آهنگین باشد
</div>

attentional hidden state
Attention mechanism 
Self-Attention 
multi-head attention
Global attention
local attention

**Comment by MohsenFayyaz89** [comment]
<div dir='rtl'>
به نظر من «توجه»  از نظر مفهوم در مباحث یادگیری ژرف مفهوم مشابه واژه اصلی رو می رسونه
</div>

**Comment by erfannoury** [comment]
<div dir="rtl">
من هم به نظرم کلمه‌ی «توجه» می‌تونه ترجمه‌ی خوبی باشه. بخصوص اگر استفاده بشه جا میوفته.
در اون صورت ترجمه‌ی عبارات بالا میشه:

* وضعیت پنهان توجه
* سازوکار توجه
* خودتوجه
* توجه چندسره (یا چندگانه)
* توجه کلی
* توجه محلی

**Comment by AlisterTA** [comment]
<div dir='rtl'>
ممنون از دوستان 

پس این issue  رو ببندیم و به لیست اصلی اضافه کنیم 
<div>

**Comment by erfannoury** [comment]
<div dir="rtl">
@m-karimi @momeni @reza1615 
شما نظری ندارید؟

**Comment by momeni** [comment]
<p dir="rtl">
از آنجا که attention در یادگیری ماشین به معنی متمرکز شدن بر روی بخشی از داده‌ها به جای تحلیل یکباره‌ی همه‌ی داده‌ها است،
<b>ژرف‌بینی</b>
یا
<b>ریزبینی</b>
که بزرگنمایی و تمرکز بر روی بخشی از داده‌ها را نشان می‌دهند مناسب به نظر می‌رسند.

**Comment by erfannoury** [comment]
<div dir="rtl">
هر چند ترجمه‌ی «توجه» به نظرم ترجمه‌ی خوبی هست ولی کلمه‌ی «ژرف‌بینی» هم فکر می‌کنم به خوبی می‌تونه این معنا رو منتقل بکنه. نظر بقیه چیه؟

**Comment by erfannoury** [comment]
<div dir="rtl">
به نظر میاد که ترجمه‌ی «ژرف‌نگری» ترجمه‌ی خوبی برای این واژه باشه.
<div>
