### ISSUE TITLE
[translation discussion] Recurrent

### ISSUE THREAD

**Issue by aaghamohammadi** [erfannoury/persian-ml-glossary#6]
<div dir="rtl">
برای کلمه 
Recurrent 
به نظرم "برگشتی" مناسب است. دکتر رضوی استاد دانشگاه تبریز هم از این کلمه استفاده می‌کنند.
[لینک](http://www.snrazavi.ir/deep-learning-glossery/)
به عنوان نمونه، 
Recurrent Neural Networks
به شبکه‌های عصبی برگشتی ترجمه شده است.
البته من درجاهایی معادل بازگشتی هم دیدم که به نظرم چندان در این جا مناسب نیست.
</div>

**Comment by erfannoury** [comment]
<div dir="rtl">
ممنون که این کلمه رو هم مطرح کردید. من هم مدتی بود که می‌خواستم بحث در این مورد رو شروع کنم ولی هنوز موفق نشدم.

مشکل ترجمه‌ی «بازگشتی» اینه که نمیشه تفاوتی برای Recursive Neural Networks  و Recurrent Neural Networks قائل شد. این دو نوع شبکه متفاوت هستن ولی ترجمه‌ی فارسی خوبی براشون وجود نداره که بشه هر دو رو متمایز کرد. نمی‌دونم چقدر ترجمه‌ی «برگشتی» ترجمه‌ی مناسبی هست ولی میشه در موردش بحث کرد.

**Comment by erfannoury** [comment]
<div dir="rtl">
و البته ممنون بخاطر لینک. منبع خیلی خوبی هست. می‌تونیم ازش (با ذکر منبع) راهنمایی بگیریم برای کامل کردن جدولی که اینجا داریم.

**Comment by aaghamohammadi** [comment]
<div dir="rtl">
دکتر رضوی اکانت گیتهاب هم دارند 
@snrazavi.
فکر کنم این ترم در حال ارائه درس یادگیری ماشین هستند. در اسلایدهایشان معادل فارسی برای دیگر کلمه های این حوزه به کار بردند.
 اسلایدهایشان در مخزن درس یادگیری ماشین  قابل دسترس است.
</div>

**Comment by erfannoury** [comment]
https://github.com/erfannoury/persian-ml-glossary/commit/57d7f820d98b20ca4a82ca5810f908b8317170e7 addresses this.
